baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Hyundai Boram'

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

oogle_analytics_id: 'UA-158921352-1'

plugins: [jekyll-environment-variables, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
