baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Hyundai Boram'

collections:
  services:
    output: true
    permalink: /products/:path/
  testimonials:
    output: true
    permalink: /about/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: 'UA-159646392-1'

plugins: [jekyll-environment-variables, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
